test:
	node_modules/.bin/babel-node tests/index.js | node_modules/.bin/tap-spec

test_arrays:
	node_modules/.bin/babel-node tests/arrays.js | node_modules/.bin/tap-spec

test_objects:
	node_modules/.bin/babel-node tests/objects.js | node_modules/.bin/tap-spec

test_strings:
	node_modules/.bin/babel-node tests/strings.js | node_modules/.bin/tap-spec

test_functions:
	node_modules/.bin/babel-node tests/functions.js | node_modules/.bin/tap-spec
